name: "Configuration testing"
on:
  pull_request:
  push:
jobs:
  Nix-Flake-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
    - run: nix flake check .
    - run: nix build
    - run: cp -rL result diagrams
    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: diagrams
        path: diagrams
